---
title: "Step 3 _analysis"
output:
  pdf_document: default
  html_document: default
date: '2022-08-11'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Importing all the required libraries.

```{r include=TRUE, echo=FALSE, message = FALSE, warning = FALSE}
library(ggm)
library(ggplot2)
library(readr)
library(pastecs)
library(readxl)
library(plyr)
library(dplyr)
library(magrittr)
library(purrr)
library(stringr)
library(QuantPsyc)
library(caTools)
library(survival)
```

## Data read before cleaning the datasets.
```{r include=TRUE,echo=FALSE, message = FALSE, warning = FALSE}
# Set the working directory and import the data from the required CSV files.

setwd('C:/Users/sandy/DSC520_SUCHI/dsc520')
# Reading the different data files that are used for the research
caffeine_df <- read.csv("data/caffeine.csv")
#head(caffeine_df)
coffeechain_df <- read.csv("data/Coffee Chain.csv")
#head(coffeechain_df)
coffeesurvey_df <- read.csv("data/Coffee_Survey.csv")
#head(coffeesurvey_df)
coffeeconsump_df <- read.csv("data/CoffeeConsumption.csv")
#head(coffeeconsump_df)
```

## First dataset

```{r include=TRUE, echo=TRUE}
caffeine_df <- read.csv("data/caffeine.csv")
head(caffeine_df)
#summary(caffeine_df)
```
```{r include=TRUE, echo=TRUE}

names(caffeine_df) <- c('DRINK', 'VOLUME', 'CALORIES', 'CAFFEINE', 'TYPE')
head(caffeine_df)
```

```{r include=TRUE, echo=TRUE}
caffeine_df <- na.omit(caffeine_df)
head(caffeine_df)

```


```{r include=TRUE, echo=TRUE}
summary(caffeine_df$TYPE)
```



```{r include=TRUE, echo=TRUE}
ggplot(caffeine_df, aes(x=CALORIES, y=CAFFEINE, col=TYPE)) + geom_point() + 
  ggtitle("calories vs. Caffeine") + xlab("Calories") + ylab("Caffeine")
```
```{r include=TRUE, echo=TRUE}
ggplot(caffeine_df, aes(x=TYPE, y=CAFFEINE)) + geom_point()+ geom_boxplot()

```

```{r include=TRUE, echo=TRUE}
ggplot(caffeine_df, aes(TYPE)) + geom_bar()

```
```{r include=TRUE, echo=TRUE}
#caffeine_df$TYPE <- as.factor(caffeine_df$TYPE)

#type_lm <-  lm( TYPE ~ CAFFEINE + CALORIES, data=caffeine_df)
#type_lm

```



```{r include=TRUE, echo=TRUE}
caffeine_df$TYPE <- as.factor(caffeine_df$TYPE)
caffeine_glm <- glm(TYPE ~ CAFFEINE + CALORIES , data = caffeine_df, family = binomial())
summary(caffeine_glm)

```

## Second dataset

```{r include=TRUE, echo=TRUE}
coffeesurvey2_df <- read.csv("data/Coffee_Survey2.csv")
head(coffeesurvey2_df)

```
```{r include=TRUE, echo=TRUE}
names(coffeesurvey2_df) <- c('drinkcoffee', 'totalcups', 'ycoffee', 'coffeeworks')
#head(coffeesurvey2_df)
coffeesurvey2_df$totalcups <- as.integer(coffeesurvey2_df$totalcups)
coffeesurvey2_df <- na.omit(coffeesurvey2_df)

#summary(coffeesurvey2_df)
```


```{r include=TRUE, echo=TRUE}

head(coffeesurvey2_df)

```

```{r include=TRUE, echo=TRUE}
ggplot(coffeesurvey2_df, aes(x=coffeeworks, y=ycoffee)) + geom_point()+ geom_boxplot()

```
```{r include=TRUE, echo=TRUE}
ggplot(coffeesurvey2_df, aes(y=ycoffee)) + geom_bar()

```


```{r include=TRUE, echo=TRUE}
ggplot(coffeesurvey2_df, aes(x=totalcups, y=drinkcoffee, col=ycoffee)) + geom_point() + 
  ggtitle("totalcups vs. drinkcoffee") + xlab("Totalcups") + ylab("Drink Coffee")
```
```{r include=TRUE, echo=TRUE}
#coffee_lm <-  lm( ycoffee ~ coffeeworks + totalcups + drinkcoffee, data=coffeesurvey2_df)
#coffee_lm

```



```{r include=TRUE, echo=TRUE}
coffeesurvey2_df$ycoffee <- as.factor(coffeesurvey2_df$ycoffee)
coffee_glm <- glm(ycoffee ~  drinkcoffee+ totalcups + coffeeworks , data = coffeesurvey2_df, family = binomial())
summary(coffee_glm)
```

```{r include=TRUE, echo=TRUE}
summary(coffeesurvey2_df$ycoffee)
```


## Third data set
```{r include=TRUE, echo=TRUE}
coffeechainFinal_df <- read.csv("data/CoffeeChainFinal.csv")
head(coffeechainFinal_df)
```

```{r include=TRUE, message = FALSE, warning = FALSE}
colnames(coffeechainFinal_df)[14] <-"CoffeeSales"
colnames(coffeechainFinal_df)[9]<- "Caffeine"
head(coffeechainFinal_df)
coffeechainFinal_df <- na.omit(coffeechainFinal_df)
```


```{r include=TRUE, message = FALSE, warning = FALSE}
ggplot(data = coffeechainFinal_df, aes(x= CoffeeSales, y=Profit, color=State)) +  geom_point()
```
```{r include=TRUE, message = FALSE, warning = FALSE}
ggplot(data = coffeechainFinal_df, aes(x= Caffeine, y=CoffeeSales, color=State)) +  geom_point()
```


```{r include=TRUE, echo=TRUE}
ggplot(coffeechainFinal_df, aes(x=CoffeeSales, y=State)) + geom_point()+ geom_boxplot()

```

```{r include=TRUE, echo=TRUE}
ggplot(coffeechainFinal_df, aes(x=Profit, y=State)) + geom_point()+ geom_boxplot()

```





```{r include=TRUE, echo=TRUE}
ggplot(coffeechainFinal_df, aes(y=State)) + geom_bar()

```

```{r include=TRUE, message = FALSE, warning = FALSE}
coffeechainFinal_df <- read.csv("data/CoffeeChainFinal.csv")
colnames(coffeechainFinal_df)[14] <-"CoffeeSales"
```


```{r include=TRUE, echo=TRUE}
summary(coffeechainFinal_df$State)
```

```{r include=TRUE, message = FALSE, warning = FALSE}
coffeesurvey2_df <- na.omit(coffeesurvey2_df)

```


```{r include=TRUE, message = FALSE, warning = FALSE}

coffeechainFinal_df$State<- as.factor(coffeechainFinal_df$State)
coffeech <- glm(State ~ CoffeeSales + Profit, data = coffeechainFinal_df, family = binomial())
summary(coffeech)
```
